< {% 
 request.variables.set("HostAddress", "http://localhost:5082")
 %}

GET {{HostAddress}}/weatherforecast/
Accept: application/json

###

< {%
    request.variables.set("HostAddress", "http://localhost:5082")
%}

POST {{HostAddress}}/UserIdentity/UserRegister
Content-Type: application/json

{
  "Username": "Test1234",
  "Password": "Password!123",
  "Email": "test123@test.com"
}

###

< {%
    request.variables.set("HostAddress", "http://localhost:5082")
%}

POST {{HostAddress}}/UserIdentity/UserLogin
Content-Type: application/json

{
  "Username": "Test1234",
  "Password": "Password!123"
}

###

< {%
    request.variables.set("HostAddress", "http://localhost:5082")
%}

POST {{HostAddress}}/UserIdentity/UserChangePassword
Content-Type: application/json

{
  "Username": "Test1234",
  "OldPassword": "Password!123",
  "NewPassword": "Password?123"
}
